# Generated by Django 5.0.3 on 2024-04-02 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_timeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelineevent',
            name='timeline',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='game.timeline'),
            preserve_default=False,
        ),
    ]
