# Generated by Django 5.0.3 on 2024-04-04 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_timelineevent_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelineevent',
            name='year',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
