# Generated by Django 5.0.3 on 2024-04-05 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_alter_timelineevent_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timelineevent',
            options={'ordering': ['date']},
        ),
        migrations.RenameField(
            model_name='timelineevent',
            old_name='year',
            new_name='date',
        ),
    ]
