# Generated by Django 5.0.3 on 2024-04-10 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_rename_timelineevent_fact'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='creator',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='timeline',
            name='description',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='timeline',
            name='keywords',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
